server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/student_analyzer_app
spring.datasource.username=postgres
spring.datasource.password=rehan's lapi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.key=AIzaSyDNrcn1MuqCZ57BUBRR6qAE-fNi3lKbGQk
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
